"""
BeyonDegrees.ai — Assertion Translation Generator
--------------------------------------------------
Reads assertions.js, translates all English texts to FR / HI / AR via
Google Translate (free, no API key), then writes assertions-i18n.js.

Features:
  • Resume support — translations cached in assertions-i18n-cache.json
  • Rate-limiting — 0.3s delay per call to avoid throttling
  • Batch retry on failure
  • Progress bar per language

Usage:
    python scripts/generate-assertions-i18n.py

Output:
    features/quiz/assertions-i18n.js
"""

import re, json, time, sys, os
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────────
BASE      = Path(__file__).parent.parent          # BeyonDegrees-UI root
SRC       = BASE / "features/quiz/assertions.js"
OUT       = BASE / "features/quiz/assertions-i18n.js"
CACHE     = BASE / "scripts/assertions-i18n-cache.json"
LANGS     = {"fr": "French", "hi": "Hindi", "ar": "Arabic"}
DELAY     = 0.35   # seconds between requests
MAX_RETRY = 3
# ────────────────────────────────────────────────────────────────────────────

def parse_assertions(path: Path) -> list[dict]:
    """Extract [{id, text}] from assertions.js using regex."""
    text = path.read_text(encoding="utf-8")
    pattern = r'\{\s*id:\s*(\d+),\s*text:\s*"([^"]+)"'
    matches = re.findall(pattern, text)
    return [{"id": int(m[0]), "text": m[1]} for m in matches]


def load_cache(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {lang: {} for lang in LANGS}


def save_cache(path: Path, cache: dict):
    path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")


def translate_text(text: str, lang_code: str) -> str:
    from deep_translator import GoogleTranslator
    for attempt in range(1, MAX_RETRY + 1):
        try:
            result = GoogleTranslator(source="en", target=lang_code).translate(text)
            return result or text
        except Exception as e:
            if attempt == MAX_RETRY:
                print(f"\n  WARN: Failed after {MAX_RETRY} attempts: {e}")
                return text
            time.sleep(1.5 * attempt)
    return text


def write_output(path: Path, cache: dict, assertions: list[dict]):
    lines = [
        "/* BeyonDegrees.ai — Assertion Translations (fr / hi / ar)       */",
        "/* Auto-generated by scripts/generate-assertions-i18n.py         */",
        "/* DO NOT edit manually — re-run the script to regenerate.       */",
        "window.BD_ASSERTIONS_I18N = {",
    ]

    lang_names = {"fr": "French", "hi": "Hindi", "ar": "Arabic"}
    lang_keys  = list(LANGS.keys())

    for i, lang in enumerate(lang_keys):
        is_last = (i == len(lang_keys) - 1)
        lines.append(f"  /* {lang_names[lang]} */")
        lines.append(f"  {lang}: {{")
        items = cache.get(lang, {})
        entry_list = []
        for a in assertions:
            sid  = str(a["id"])
            val  = items.get(sid, a["text"]).replace("\\", "\\\\").replace('"', '\\"')
            entry_list.append(f'    {sid}: "{val}"')
        lines.append(",\n".join(entry_list))
        lines.append("  }" + ("," if not is_last else ""))

    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    # Force UTF-8 output on Windows
    if sys.platform == "win32":
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

    print("BeyonDegrees Assertion Translator")
    print("=" * 50)

    # 1. Parse
    assertions = parse_assertions(SRC)
    total = len(assertions)
    print(f"  Parsed {total} assertions from {SRC.name}")

    # 2. Load cache
    cache = load_cache(CACHE)
    print(f"  Cache loaded from {CACHE.name if CACHE.exists() else '(new)'}")

    # 3. Translate missing entries per language
    for lang, lang_name in LANGS.items():
        missing = [a for a in assertions if str(a["id"]) not in cache.get(lang, {})]
        if not missing:
            print(f"\n  OK {lang_name} ({lang}): all {total} already translated")
            continue

        done = total - len(missing)
        print(f"\n  >> {lang_name} ({lang}): {done}/{total} cached, translating {len(missing)} new...")

        for idx, a in enumerate(missing, 1):
            translated = translate_text(a["text"], lang)
            cache.setdefault(lang, {})[str(a["id"])] = translated

            # Print progress every 10 or at end
            if idx % 10 == 0 or idx == len(missing):
                pct = int((done + idx) / total * 100)
                bar = "#" * (pct // 5) + "." * (20 - pct // 5)
                print(f"    [{bar}] {done+idx}/{total} ({pct}%)  id={a['id']}", end="\r", flush=True)

            time.sleep(DELAY)

        save_cache(CACHE, cache)
        print(f"\n  [saved] Cache saved after {lang_name}")

    # 4. Write output
    write_output(OUT, cache, assertions)
    print(f"\nDONE! Written to: {OUT}")
    print(f"   Total entries: {total} assertions x 3 languages = {total*3}")


if __name__ == "__main__":
    main()
